// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wire} from '../models';
import {main} from '../models';

export function AcceptLLMRun(arg1:string,arg2:wire.AcceptRunRequest):Promise<wire.TaskList>;

export function AssistantChat(arg1:wire.AssistantChatRequest):Promise<wire.LlmRun>;

export function Autostart():Promise<boolean>;

export function BreakEnd():Promise<wire.Status>;

export function BreakStart():Promise<wire.Status>;

export function Briefing():Promise<wire.Briefing>;

export function CalendarAuthStart():Promise<wire.CalendarAuth>;

export function CalendarCalendars():Promise<wire.CalendarList>;

export function CalendarStatus():Promise<wire.CalendarStatus>;

export function CalendarSync():Promise<wire.CalendarStatus>;

export function CancelListening():Promise<void>;

export function ChooseGoogleClient():Promise<boolean>;

export function ClaudeCode(arg1:string):Promise<main.ClaudeCodeStatus>;

export function ClockIn(arg1:wire.ClockInRequest):Promise<wire.Status>;

export function ClockOut():Promise<wire.Status>;

export function CompleteTask(arg1:string,arg2:wire.CompleteTaskRequest):Promise<wire.Task>;

export function CreateCommitment(arg1:wire.CreateCommitmentRequest):Promise<wire.Commitment>;

export function CreateGoal(arg1:wire.CreateGoalRequest):Promise<wire.Goal>;

export function CreateProject(arg1:wire.CreateProjectRequest):Promise<wire.Project>;

export function CreateSegment(arg1:wire.CreateSegmentRequest):Promise<wire.Segment>;

export function CreateTask(arg1:wire.CreateTaskRequest):Promise<wire.Task>;

export function DeleteCommitment(arg1:string):Promise<void>;

export function DeleteEnergy(arg1:string):Promise<void>;

export function DeleteGoal(arg1:string,arg2:boolean):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteSegment(arg1:string):Promise<void>;

export function DeleteTask(arg1:string):Promise<void>;

export function DeleteTasks(arg1:wire.DeleteTasksRequest):Promise<wire.DeletedTasks>;

export function EnableService():Promise<void>;

export function EnergyReport(arg1:number):Promise<wire.EnergyReport>;

export function GeneratePlan(arg1:wire.GeneratePlanRequest):Promise<wire.Plan>;

export function GetConfig():Promise<wire.Config>;

export function GetDay(arg1:string):Promise<wire.DayDetail>;

export function GetGoal(arg1:string):Promise<wire.Goal>;

export function GetLLMRun(arg1:string):Promise<wire.LlmRun>;

export function GetPlan(arg1:string):Promise<wire.Plan>;

export function GetProject(arg1:string):Promise<wire.Project>;

export function GetReview(arg1:string):Promise<wire.WeeklyReview>;

export function GetTask(arg1:string):Promise<wire.Task>;

export function GoalBreakdown(arg1:string,arg2:wire.BreakdownRequest):Promise<wire.LlmRun>;

export function HasCredential(arg1:string):Promise<boolean>;

export function Health():Promise<wire.Health>;

export function InstallVoice():Promise<void>;

export function IsNowCard():Promise<boolean>;

export function ListCommitments():Promise<wire.CommitmentList>;

export function ListDays(arg1:string,arg2:string):Promise<wire.DayList>;

export function ListGoals(arg1:string):Promise<wire.GoalList>;

export function ListProjects(arg1:string):Promise<wire.ProjectList>;

export function ListTasks(arg1:wire.TaskQuery):Promise<wire.TaskList>;

export function LogEnergy(arg1:wire.LogEnergyRequest):Promise<wire.EnergyLog>;

export function MovePlanTask(arg1:wire.MovePlanTaskRequest):Promise<wire.Plan>;

export function NewTopic():Promise<string>;

export function NotifyTest():Promise<wire.NotifyTestResult>;

export function OpenDashboard(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function PatchCommitment(arg1:string,arg2:wire.PatchCommitmentRequest):Promise<wire.Commitment>;

export function PatchConfig(arg1:wire.ConfigPatch):Promise<wire.Config>;

export function PatchDay(arg1:string,arg2:wire.PatchDayRequest):Promise<wire.WorkDay>;

export function PatchGoal(arg1:string,arg2:wire.PatchGoalRequest):Promise<wire.Goal>;

export function PatchPlanItem(arg1:string,arg2:wire.PatchPlanItemRequest):Promise<wire.PlanItem>;

export function PatchProject(arg1:string,arg2:wire.PatchProjectRequest):Promise<wire.Project>;

export function PatchSegment(arg1:string,arg2:wire.PatchSegmentRequest):Promise<wire.Segment>;

export function PatchTask(arg1:string,arg2:wire.PatchTaskRequest):Promise<wire.Task>;

export function PlanChat(arg1:wire.PlanChatRequest):Promise<wire.LlmRun>;

export function PreviewGoal(arg1:wire.GoalPreviewRequest):Promise<wire.GoalProgress>;

export function RejectLLMRun(arg1:string):Promise<wire.LlmRun>;

export function RemoveVoice():Promise<void>;

export function ReopenTask(arg1:string):Promise<wire.Task>;

export function Retro(arg1:wire.RetroRequest):Promise<wire.LlmRun>;

export function SaveReview(arg1:string,arg2:wire.SaveReviewRequest):Promise<wire.WeeklyReview>;

export function ScheduleTask(arg1:wire.ScheduleRequest):Promise<wire.PlanItem>;

export function SetAutostart(arg1:boolean):Promise<void>;

export function SetCredential(arg1:string,arg2:string):Promise<void>;

export function SetDayHours(arg1:wire.SetDayHoursRequest):Promise<wire.Plan>;

export function Snooze():Promise<wire.Status>;

export function SplitSegment(arg1:string,arg2:wire.SplitSegmentRequest):Promise<wire.SegmentList>;

export function StartListening():Promise<void>;

export function StartScreen():Promise<string>;

export function StatsHeatmap(arg1:number):Promise<wire.Heatmap>;

export function StatsSummary(arg1:string,arg2:string):Promise<wire.StatsSummary>;

export function Status():Promise<wire.Status>;

export function StopListening():Promise<string>;

export function Switch(arg1:wire.SwitchRequest):Promise<wire.Status>;

export function SyncNow():Promise<wire.SyncStatus>;

export function SyncStatus():Promise<wire.SyncStatus>;

export function UnscheduleTask(arg1:wire.UnscheduleRequest):Promise<wire.Unscheduled>;

export function Version():Promise<string>;

export function VoiceStatus():Promise<main.VoiceStatus>;
