// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptLLMRun(arg1, arg2) {
  return window['go']['main']['App']['AcceptLLMRun'](arg1, arg2);
}

export function AssistantChat(arg1) {
  return window['go']['main']['App']['AssistantChat'](arg1);
}

export function Autostart() {
  return window['go']['main']['App']['Autostart']();
}

export function BreakEnd() {
  return window['go']['main']['App']['BreakEnd']();
}

export function BreakStart() {
  return window['go']['main']['App']['BreakStart']();
}

export function Briefing() {
  return window['go']['main']['App']['Briefing']();
}

export function CalendarAuthStart() {
  return window['go']['main']['App']['CalendarAuthStart']();
}

export function CalendarStatus() {
  return window['go']['main']['App']['CalendarStatus']();
}

export function CalendarSync() {
  return window['go']['main']['App']['CalendarSync']();
}

export function ChooseGoogleClient() {
  return window['go']['main']['App']['ChooseGoogleClient']();
}

export function ClaudeCode(arg1) {
  return window['go']['main']['App']['ClaudeCode'](arg1);
}

export function ClockIn(arg1) {
  return window['go']['main']['App']['ClockIn'](arg1);
}

export function ClockOut() {
  return window['go']['main']['App']['ClockOut']();
}

export function CompleteTask(arg1, arg2) {
  return window['go']['main']['App']['CompleteTask'](arg1, arg2);
}

export function CreateCommitment(arg1) {
  return window['go']['main']['App']['CreateCommitment'](arg1);
}

export function CreateGoal(arg1) {
  return window['go']['main']['App']['CreateGoal'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function CreateSegment(arg1) {
  return window['go']['main']['App']['CreateSegment'](arg1);
}

export function CreateTask(arg1) {
  return window['go']['main']['App']['CreateTask'](arg1);
}

export function DeleteCommitment(arg1) {
  return window['go']['main']['App']['DeleteCommitment'](arg1);
}

export function DeleteEnergy(arg1) {
  return window['go']['main']['App']['DeleteEnergy'](arg1);
}

export function DeleteGoal(arg1, arg2) {
  return window['go']['main']['App']['DeleteGoal'](arg1, arg2);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteSegment(arg1) {
  return window['go']['main']['App']['DeleteSegment'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function DeleteTasks(arg1) {
  return window['go']['main']['App']['DeleteTasks'](arg1);
}

export function EnableService() {
  return window['go']['main']['App']['EnableService']();
}

export function EnergyReport(arg1) {
  return window['go']['main']['App']['EnergyReport'](arg1);
}

export function GeneratePlan(arg1) {
  return window['go']['main']['App']['GeneratePlan'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDay(arg1) {
  return window['go']['main']['App']['GetDay'](arg1);
}

export function GetGoal(arg1) {
  return window['go']['main']['App']['GetGoal'](arg1);
}

export function GetLLMRun(arg1) {
  return window['go']['main']['App']['GetLLMRun'](arg1);
}

export function GetPlan(arg1) {
  return window['go']['main']['App']['GetPlan'](arg1);
}

export function GetProject(arg1) {
  return window['go']['main']['App']['GetProject'](arg1);
}

export function GetReview(arg1) {
  return window['go']['main']['App']['GetReview'](arg1);
}

export function GetTask(arg1) {
  return window['go']['main']['App']['GetTask'](arg1);
}

export function GoalBreakdown(arg1, arg2) {
  return window['go']['main']['App']['GoalBreakdown'](arg1, arg2);
}

export function HasCredential(arg1) {
  return window['go']['main']['App']['HasCredential'](arg1);
}

export function Health() {
  return window['go']['main']['App']['Health']();
}

export function ListCommitments() {
  return window['go']['main']['App']['ListCommitments']();
}

export function ListDays(arg1, arg2) {
  return window['go']['main']['App']['ListDays'](arg1, arg2);
}

export function ListGoals(arg1) {
  return window['go']['main']['App']['ListGoals'](arg1);
}

export function ListProjects(arg1) {
  return window['go']['main']['App']['ListProjects'](arg1);
}

export function ListTasks(arg1) {
  return window['go']['main']['App']['ListTasks'](arg1);
}

export function LogEnergy(arg1) {
  return window['go']['main']['App']['LogEnergy'](arg1);
}

export function NewTopic() {
  return window['go']['main']['App']['NewTopic']();
}

export function NotifyTest() {
  return window['go']['main']['App']['NotifyTest']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PatchCommitment(arg1, arg2) {
  return window['go']['main']['App']['PatchCommitment'](arg1, arg2);
}

export function PatchConfig(arg1) {
  return window['go']['main']['App']['PatchConfig'](arg1);
}

export function PatchDay(arg1, arg2) {
  return window['go']['main']['App']['PatchDay'](arg1, arg2);
}

export function PatchGoal(arg1, arg2) {
  return window['go']['main']['App']['PatchGoal'](arg1, arg2);
}

export function PatchPlanItem(arg1, arg2) {
  return window['go']['main']['App']['PatchPlanItem'](arg1, arg2);
}

export function PatchProject(arg1, arg2) {
  return window['go']['main']['App']['PatchProject'](arg1, arg2);
}

export function PatchSegment(arg1, arg2) {
  return window['go']['main']['App']['PatchSegment'](arg1, arg2);
}

export function PatchTask(arg1, arg2) {
  return window['go']['main']['App']['PatchTask'](arg1, arg2);
}

export function PlanChat(arg1) {
  return window['go']['main']['App']['PlanChat'](arg1);
}

export function PreviewGoal(arg1) {
  return window['go']['main']['App']['PreviewGoal'](arg1);
}

export function RejectLLMRun(arg1) {
  return window['go']['main']['App']['RejectLLMRun'](arg1);
}

export function ReopenTask(arg1) {
  return window['go']['main']['App']['ReopenTask'](arg1);
}

export function Retro(arg1) {
  return window['go']['main']['App']['Retro'](arg1);
}

export function SaveReview(arg1, arg2) {
  return window['go']['main']['App']['SaveReview'](arg1, arg2);
}

export function ScheduleTask(arg1) {
  return window['go']['main']['App']['ScheduleTask'](arg1);
}

export function SetAutostart(arg1) {
  return window['go']['main']['App']['SetAutostart'](arg1);
}

export function SetCredential(arg1, arg2) {
  return window['go']['main']['App']['SetCredential'](arg1, arg2);
}

export function SetDayHours(arg1) {
  return window['go']['main']['App']['SetDayHours'](arg1);
}

export function Snooze() {
  return window['go']['main']['App']['Snooze']();
}

export function SplitSegment(arg1, arg2) {
  return window['go']['main']['App']['SplitSegment'](arg1, arg2);
}

export function StartScreen() {
  return window['go']['main']['App']['StartScreen']();
}

export function StatsHeatmap(arg1) {
  return window['go']['main']['App']['StatsHeatmap'](arg1);
}

export function StatsSummary(arg1, arg2) {
  return window['go']['main']['App']['StatsSummary'](arg1, arg2);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function Switch(arg1) {
  return window['go']['main']['App']['Switch'](arg1);
}

export function SyncNow() {
  return window['go']['main']['App']['SyncNow']();
}

export function SyncStatus() {
  return window['go']['main']['App']['SyncStatus']();
}

export function UnscheduleTask(arg1) {
  return window['go']['main']['App']['UnscheduleTask'](arg1);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
