// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wire} from '../models';

export function Autostart():Promise<boolean>;

export function BreakEnd():Promise<wire.Status>;

export function BreakStart():Promise<wire.Status>;

export function ClockIn(arg1:wire.ClockInRequest):Promise<wire.Status>;

export function ClockOut():Promise<wire.Status>;

export function CompleteTask(arg1:string,arg2:wire.CompleteTaskRequest):Promise<wire.Task>;

export function CreateProject(arg1:wire.CreateProjectRequest):Promise<wire.Project>;

export function CreateSegment(arg1:wire.CreateSegmentRequest):Promise<wire.Segment>;

export function CreateTask(arg1:wire.CreateTaskRequest):Promise<wire.Task>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteSegment(arg1:string):Promise<void>;

export function DeleteTask(arg1:string):Promise<void>;

export function EnableService():Promise<void>;

export function GetConfig():Promise<wire.Config>;

export function GetDay(arg1:string):Promise<wire.DayDetail>;

export function GetProject(arg1:string):Promise<wire.Project>;

export function GetTask(arg1:string):Promise<wire.Task>;

export function Health():Promise<wire.Health>;

export function ListDays(arg1:string,arg2:string):Promise<wire.DayList>;

export function ListProjects(arg1:string):Promise<wire.ProjectList>;

export function ListTasks(arg1:wire.TaskQuery):Promise<wire.TaskList>;

export function NewTopic():Promise<string>;

export function NotifyTest():Promise<wire.NotifyTestResult>;

export function OpenURL(arg1:string):Promise<void>;

export function PatchConfig(arg1:wire.ConfigPatch):Promise<wire.Config>;

export function PatchDay(arg1:string,arg2:wire.PatchDayRequest):Promise<wire.WorkDay>;

export function PatchProject(arg1:string,arg2:wire.PatchProjectRequest):Promise<wire.Project>;

export function PatchSegment(arg1:string,arg2:wire.PatchSegmentRequest):Promise<wire.Segment>;

export function PatchTask(arg1:string,arg2:wire.PatchTaskRequest):Promise<wire.Task>;

export function ReopenTask(arg1:string):Promise<wire.Task>;

export function SetAutostart(arg1:boolean):Promise<void>;

export function SetCredential(arg1:string,arg2:string):Promise<void>;

export function Snooze():Promise<wire.Status>;

export function SplitSegment(arg1:string,arg2:wire.SplitSegmentRequest):Promise<wire.SegmentList>;

export function StatsHeatmap(arg1:number):Promise<wire.Heatmap>;

export function StatsSummary(arg1:string,arg2:string):Promise<wire.StatsSummary>;

export function Status():Promise<wire.Status>;

export function Switch(arg1:wire.SwitchRequest):Promise<wire.Status>;

export function Version():Promise<string>;
